<?php 

function pdm_db_install(){
    global $wpdb;
    global $pdm_version;

    $charset_collate = $wpdb->get_charset_collate();

    require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );

    $sql = "
    -- MySQL Script generated by MySQL Workbench
    -- 12/28/16 04:25:21
    -- Model: New Model    Version: 1.0
    -- MySQL Workbench Forward Engineering

    SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
    SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
    SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


    -- -----------------------------------------------------
    -- Table `pdm_pasajero` PASAJEROS
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_pasajero` (
      `pdm_pasajero_id` INT NOT NULL AUTO_INCREMENT,
      `pdm_pasajero_nombres` VARCHAR(150) NOT NULL,
      `pdm_pasajero_apellidos` VARCHAR(150) NULL,
      `pdm_pasajero_nacionalidad` VARCHAR(200) NULL,
      `pdm_pasajero_genero` VARCHAR(50) NULL,
      `pdm_pasajero_nacimiento` DATE NULL,
      `pdm_pasajero_notas` TEXT NULL,
      `pdm_pasajero_foto` VARCHAR(200) NULL,
      PRIMARY KEY (`pdm_pasajero_id`))
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );

    $sql ="
    -- -----------------------------------------------------
    -- Table `pdm_telefono` TELÉFONOS
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_telefono` (
      `pdm_telefono_id` INT NOT NULL AUTO_INCREMENT,
      `pdm_telefono_numero` VARCHAR(80) NULL,
      PRIMARY KEY (`pdm_telefono_id`))
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );
    
    $sql="
    -- -----------------------------------------------------
    -- Table `pdm_correo` CORREOS
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_correo` (
      `pdm_correo_id` INT NOT NULL AUTO_INCREMENT,
      `pdm_correo_correo` VARCHAR(150) NULL,
      PRIMARY KEY (`pdm_correo_id`))
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );

    $sql="
    -- -----------------------------------------------------
    -- Table `pdm_direccion` DIRECCIONES
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_direccion` (
      `pdm_direccion_id` INT NOT NULL AUTO_INCREMENT,
      `pdm_direccion_nombre` VARCHAR(150) NOT NULL,
      `pdm_direccion_distrito` VARCHAR(150) NULL,
      `pdm_direccion_ciudad` VARCHAR(200) NULL,
      `pdm_direccion_pais` VARCHAR(200) NULL,
      PRIMARY KEY (`pdm_direccion_id`))
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );
    
    $sql="
    -- -----------------------------------------------------
    -- Table `pdm_identificacion` IDENTIFICACIÓN
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_identificacion` (
      `pdm_identificacion_id` INT NOT NULL AUTO_INCREMENT,
      `pdm_identificacion_tipo` VARCHAR(45) NULL,
      `pdm_identificacion_numero` VARCHAR(60) NOT NULL,
      `pdm_identificacion_pais` VARCHAR(200) NULL,
      `pdm_identificacion_emision` DATE NULL,
      `pdm_identificacion_vencimiento` DATE NULL,
      `pdm_identificacion_nota` TEXT NULL,
      `pdm_identificacion_foto` VARCHAR(200) NULL,
      PRIMARY KEY (`pdm_identificacion_id`))
    $charset_collate
    ENGINE = InnoDB;";    
    dbDelta( $sql );

    $sql="
    -- -----------------------------------------------------
    -- Table `pdm_paxtel` PAX->TELEFONO
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_paxtel` (
      `pdm_paxtel_pasajero_ID` INT NOT NULL,
      `pdm_paxtel_telefono_ID` INT NOT NULL)
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );

    $sql = "
    -- -----------------------------------------------------
    -- Table `pdm_paxcor` PAX->CORREO
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_paxcor` (
      `pdm_paxcor_pasajero_ID` INT NOT NULL,
      `pdm_paxcor_correo_ID` INT NOT NULL)
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );

    $sql = "
    -- -----------------------------------------------------
    -- Table `pdm_paxdir` PAX->DIRECCION
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_paxdir` (
      `pdm_paxdir_pasajero_ID` INT NOT NULL,
      `pdm_paxdir_direccion_ID` INT NOT NULL)
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );

    $sql = "
    -- -----------------------------------------------------
    -- Table `pdm_paxid` PAX->IDENTIFICACION
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_paxid` (
      `pdm_paxid_pasajero_ID` INT NOT NULL,
      `pdm_paxid_identificacion_ID` INT NOT NULL)
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );
    
    $sql ="
    -- -----------------------------------------------------
    -- Table pdm_solicitud`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_solicitud` (
      `pdm_solicitud_id` INT NOT NULL AUTO_INCREMENT,
      `pdm_solicitud_inicio` DATETIME NULL,
      `pdm_solicitud_fin` DATETIME NULL,
      `pdm_solicitud_usuario` INT NULL,
      `pdm_solicitud_responsable` INT NULL,
      `pdm_solicitud_estado` VARCHAR(45) NULL,
      `pdm_solicitud_pasajero_ID` INT NULL,
      `pdm_solicitud_servicios` VARCHAR(150) NULL,
      `pdm_solicitud_fecha_tipo` VARCHAR(20) NULL,
      `pdm_solicitud_fecha_salida` DATE NULL,
      `pdm_solicitud_fecha_retorno` DATE NULL,
      `pdm_solicitud_origen` VARCHAR(150) NULL,
      `pdm_solicitud_destino` VARCHAR(150) NULL,
      `pdm_solicitud_cantidad_adt` INT NULL,
      `pdm_solicitud_cantidad_chd` INT NULL,
      `pdm_solicitud_cantidad_inf` INT NULL,
      `pdm_solicitud_descripcion` TEXT NULL,
      PRIMARY KEY (`pdm_solicitud_id`))
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );

    $sql ="
    -- -----------------------------------------------------
    -- Table `pdm`.`pdm_solicitud_historial`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `pdm_solicitud_historial` (
      `pdm_solicitud_historial_id` INT NOT NULL AUTO_INCREMENT,
      `pdm_solicitud_historial_usuario` INT NULL,
      `pdm_solicitud_historial_fecha` DATETIME NULL,
      `pdm_solicitud_historial_comentario` TEXT NULL,
      `pdm_solicitud_historial_solID` INT NULL,
      PRIMARY KEY (`pdm_solicitud_historial_id`))
    $charset_collate
    ENGINE = InnoDB;";
    dbDelta( $sql );

}
?>